server:
  port: 9000
eureka:
  instance:
    hostname: 127.0.0.1
    prefer-ip-address: true
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
